# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.prometheus_operator.v1 import Alertmanager as _Resource0
    from cloudcoil.models.prometheus_operator.v1 import PodMonitor as _Resource2
    from cloudcoil.models.prometheus_operator.v1 import Probe as _Resource3
    from cloudcoil.models.prometheus_operator.v1 import Prometheus as _Resource4
    from cloudcoil.models.prometheus_operator.v1 import PrometheusRule as _Resource6
    from cloudcoil.models.prometheus_operator.v1 import ServiceMonitor as _Resource8
    from cloudcoil.models.prometheus_operator.v1 import ThanosRuler as _Resource9
    from cloudcoil.models.prometheus_operator.v1alpha1 import AlertmanagerConfig as _Resource1
    from cloudcoil.models.prometheus_operator.v1alpha1 import PrometheusAgent as _Resource5
    from cloudcoil.models.prometheus_operator.v1alpha1 import ScrapeConfig as _Resource7

_MODELS = {
    ("Alertmanager", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "Alertmanager",
    ),
    ("Alertmanager", ""): ("cloudcoil.models.prometheus_operator.v1", "Alertmanager"),
    ("AlertmanagerConfig", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "AlertmanagerConfig",
    ),
    ("AlertmanagerConfig", ""): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "AlertmanagerConfig",
    ),
    ("PodMonitor", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "PodMonitor",
    ),
    ("PodMonitor", ""): ("cloudcoil.models.prometheus_operator.v1", "PodMonitor"),
    ("Probe", "monitoring.coreos.com/v1"): ("cloudcoil.models.prometheus_operator.v1", "Probe"),
    ("Probe", ""): ("cloudcoil.models.prometheus_operator.v1", "Probe"),
    ("Prometheus", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "Prometheus",
    ),
    ("Prometheus", ""): ("cloudcoil.models.prometheus_operator.v1", "Prometheus"),
    ("PrometheusAgent", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "PrometheusAgent",
    ),
    ("PrometheusAgent", ""): ("cloudcoil.models.prometheus_operator.v1alpha1", "PrometheusAgent"),
    ("PrometheusRule", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "PrometheusRule",
    ),
    ("PrometheusRule", ""): ("cloudcoil.models.prometheus_operator.v1", "PrometheusRule"),
    ("ScrapeConfig", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "ScrapeConfig",
    ),
    ("ScrapeConfig", ""): ("cloudcoil.models.prometheus_operator.v1alpha1", "ScrapeConfig"),
    ("ServiceMonitor", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "ServiceMonitor",
    ),
    ("ServiceMonitor", ""): ("cloudcoil.models.prometheus_operator.v1", "ServiceMonitor"),
    ("ThanosRuler", "monitoring.coreos.com/v1"): (
        "cloudcoil.models.prometheus_operator.v1",
        "ThanosRuler",
    ),
    ("ThanosRuler", ""): ("cloudcoil.models.prometheus_operator.v1", "ThanosRuler"),
}


@overload
def get_model(
    kind: Literal["Alertmanager"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["Alertmanager"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["AlertmanagerConfig"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["AlertmanagerConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["PodMonitor"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["PodMonitor"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["Probe"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(kind: Literal["Probe"], *, api_version: Literal[""] = "") -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Prometheus"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["Prometheus"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["PrometheusAgent"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["PrometheusAgent"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["PrometheusRule"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["PrometheusRule"], *, api_version: Literal[""] = ""
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["ScrapeConfig"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ScrapeConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ServiceMonitor"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ServiceMonitor"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["ThanosRuler"], *, api_version: Literal["monitoring.coreos.com/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["ThanosRuler"], *, api_version: Literal[""] = ""
) -> type[_Resource9]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
