# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.prometheus_operator.v1alpha1 import AlertmanagerConfig as _Resource0
    from cloudcoil.models.prometheus_operator.v1alpha1 import PrometheusAgent as _Resource1
    from cloudcoil.models.prometheus_operator.v1alpha1 import ScrapeConfig as _Resource2

_MODELS = {
    ("AlertmanagerConfig", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "AlertmanagerConfig",
    ),
    ("AlertmanagerConfig", ""): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "AlertmanagerConfig",
    ),
    ("PrometheusAgent", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "PrometheusAgent",
    ),
    ("PrometheusAgent", ""): ("cloudcoil.models.prometheus_operator.v1alpha1", "PrometheusAgent"),
    ("ScrapeConfig", "monitoring.coreos.com/v1alpha1"): (
        "cloudcoil.models.prometheus_operator.v1alpha1",
        "ScrapeConfig",
    ),
    ("ScrapeConfig", ""): ("cloudcoil.models.prometheus_operator.v1alpha1", "ScrapeConfig"),
}


@overload
def get_model(
    kind: Literal["AlertmanagerConfig"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["AlertmanagerConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["PrometheusAgent"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["PrometheusAgent"], *, api_version: Literal[""] = ""
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ScrapeConfig"], *, api_version: Literal["monitoring.coreos.com/v1alpha1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ScrapeConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource2]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
